### ISSUE TITLE
Manim error - Lissajous Curve Table animation

### ISSUE THREAD

**Issue by ghost** [abhi3019/manim-projects#1]
Hi, I would like to render the video "Lissajous Curve Table animation" with manim as well.  However, I can't get it to work with either the community version or the 3b1b manim version. What am I doing wrong?

Here's what happens with the 3b1b version.
![image](https://user-images.githubusercontent.com/15014849/129738902-cc0afbc9-427b-4c45-9b28-09c20e1f3940.png)

With the community version also come more than bugs. However, it is the source code that breaks down and not manim itself.

![image](https://user-images.githubusercontent.com/15014849/129739491-bff78a89-9226-4ae3-b8eb-23ca254e1c5b.png)

But maybe I'm doing something completely wrong. Can you help me?

With kind regards
@Zeyecx

**Comment by abhijithmuthyala** [comment]
> However, I can't get it to work with either the community version or the 3b1b manim version

Hi, that project was made with the community version and since it has diverged very much from the 3b1b version, it isn't surprising that it doesn't work with 3b1b's version.

> But maybe I'm doing something completely wrong

Nothing wrong from your side I believe, it's just a consequence of manim's code updating constantly so some parts of old code might need some modifications.

I've just pushed the fix, can you try it now by pulling the changes?

**Comment by ghost** [comment]
Hello. 
I made a pull and re-run manimgl. The manim version of 3b1b still does not work. However, the community version seems to work now without problems. 
![image](https://user-images.githubusercontent.com/15014849/129746631-0265c58c-897f-4dc4-82c3-d19bd7f1a7ae.png)
![image](https://user-images.githubusercontent.com/15014849/129747007-e067c001-82e1-45a0-afc1-e4eaca684bcf.png)
However, I think the problems are in the Manim version of 3b1b, because other projects with the 3b1b version I could not render either 
With kind regards
@Zeyecx
